### ISSUE TITLE
Does Martin support dynamically refreshing PostGIS tables?

### ISSUE THREAD

**Issue by xyzhuo** [urbica/martin#1467] opened 2024-08-14 16:19 UTC
Please, I use Martin to link to PostGIS, and then use qgis data manager to import a new shafile into PostGIS as a new source, but I can't see the new source in Martin. Does Martin support dynamically refreshing PostGIS tables?

**Comment by nyurik** [comment] 2024-08-14 16:22
It has been a long-requested feature - duplicate of #288

**Closed as not planned by nyurik** 2024-08-14 16:22 UTC

**Comment by xyzhuo** [comment] 2024-08-14 16:32
Thanks.
