### ISSUE TITLE
Cache invalidation problems when database content changes

### ISSUE THREAD

**Issue by mkovac-conductive** [urbica/martin#1578] opened 2024-11-14 12:57 UTC
I would like to know what is the recommended way to handle tile cache invalidation when database content changes? Currently I need to restart martin server to get latest data on my Mapbox page.

My setup:

Frontend: React (with Mapbox)
Tileserver: Martin
Database: PostgreSQL

Thanks!

**Comment by CommanderStorm** [comment] 2024-11-14 20:13
Currently, restarting is the only option.

While this should be pretty quick, this is not ideal (we know).
The current draft of an API route for this would be a massive performance hit and has thus not been merged.

See
- https://github.com/maplibre/martin/pull/1179

**Comment by CommanderStorm** [comment] 2024-11-15 22:51
I think we should track this in https://github.com/maplibre/martin/issues/https://github.com/maplibre/martin/issues/288 instead, given that said issue already has a discussion about how this can/should be implemented

=> Closing as a duplicate of #288 ^^

**Closed as not planned by CommanderStorm** 2024-11-15 22:51 UTC

**Comment by nyurik** [comment] 2024-11-15 23:17
I keep wondering if we should kill the tile cache for now - it is more of a nuicance than help - response caching can be done much better at the load balancer or reverse proxy level (e.g. GCP Load balancer / Varnish / Nginx / ...).

The only real reason for cache (why i initially introduced it) - was to cache pmtiles directory structure so it doesn't need to be refetched for each tile
