### ISSUE TITLE
[FR] Serving mbtiles/pmtiles from cloud storage (S3 or any other)

### ISSUE THREAD

**Issue by AbelVM** [urbica/martin#801] opened 2023-08-11 08:12 UTC
As of today, Martin only serves tiles from locally stored files, it would be great to add the ability to serve tiles from files stored in cloud storage.

**Comment by nyurik** [comment] 2023-10-22 02:46
@AbelVM I agree :100: -- it is already being tracked in #884 for PMTiles.  I do not believe it will be possible to serve MBTiles from a cloud storage though because SQLite database is optimized for local disk access (block devices), so even though I have seen a hack where a website was using sqlite binary in a webassembly to request the actual data from the server, it is far from efficient. In other words - lets focus on pmtiles for this usecase - help wanted :)

Closing as a duplicate of #884

**Closed as completed by nyurik** 2023-10-22 02:46 UTC
