### ISSUE TITLE
How to server custom font via Martin

### ISSUE THREAD

**Issue by CNFeffery** [urbica/martin#821] opened 2023-08-17 13:25 UTC
I can't find that in the documentation.

**Comment by nyurik** [comment] 2023-08-20 05:19
It cannot be done yet.  I have started some work on that https://github.com/maplibre/martin/pull/755 but for now you have to use some other method of serving static content, e.g. nginx, and proxy requests to martin

**Comment by nyurik** [comment] 2023-10-22 02:50
Closing this as a duplicate of #704

**Closed as completed by nyurik** 2023-10-22 02:50 UTC
Labels: question
